# Generated by Django 6.0.7 on 2026-07-29 10:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_id', models.CharField(max_length=50)),
                ('service_type', models.CharField(choices=[('BUSINESS_PERMIT', 'Single Business Permit'), ('LAND_RATES', 'Land Rates Valuation'), ('BURSARY', 'Education Bursary Allocation'), ('HEALTH_CERT', 'Public Health Certificate')], max_length=30)),
                ('status', models.CharField(default='SUBMITTED', max_length=30)),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('payload_data', models.JSONField(default=dict, help_text='Form field responses unique to the service')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CountyNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_id', models.CharField(help_text='e.g., KE-COUNTY-047', max_length=50)),
                ('service_type', models.CharField(choices=[('BUSINESS_PERMIT', 'Single Business Permit'), ('LAND_RATES', 'Land Rates Valuation'), ('BURSARY', 'Education Bursary Allocation'), ('HEALTH_CERT', 'Public Health Certificate')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('requirements', models.JSONField(default=list, help_text='List of string requirements')),
                ('source_url', models.URLField(max_length=500)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-deadline', '-scraped_at'],
                'indexes': [models.Index(fields=['county_id', 'service_type'], name='Service_Tra_county__ee856a_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('role', models.CharField(choices=[('ADMIN', 'System Administrator'), ('OFFICER', 'County Government Officer'), ('CITIZEN', 'Standard Citizen Account')], default='CITIZEN', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('county_code', models.CharField(blank=True, help_text='Target region tag if role is OFFICER', max_length=10, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(max_length=30)),
                ('to_state', models.CharField(max_length=30)),
                ('comment', models.TextField(blank=True, help_text='Reviewer remarks or correction prompts', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='Service_Tracker.application')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='citizen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['tracking_number'], name='Service_Tra_trackin_c4765b_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='Service_Tra_status_aa5d99_idx'),
        ),
    ]
