import logging
logger= logging.getlogger(__name__)

STATE_SUBMITTED= "SUBMIT"
STATE_UNDER_REVIEW= "UNDER_REVIEW"
STATE_ACTION_REQUIRED= "ACTION_REQUIRED"
STATE_VERIFIED= "VERIFIED"
STATE_APPROVED= "APPROVED"
STATE_REJECT= "REJECT" 

VALID_STATES={
    STATE_SUBMITTED,
    STATE_UNDER_REVIEW,
    STATE_ACTION_REQUIRED,
    STATE_VERIFIED,
    STATE_APPROVED,
    STATE_REJECT
}
