import logging
logger= logging.getlogger(__name__)

STATE_SUBMITTED= "SUBMIT"
STATE_UNDER_REVIEW= "UNDER_REVIEW"
STATE_ACTION_REQUIRED= "ACTION_REQUIRED"
STATE_VERIFIED= "VERIFIED"
STATE_APPROVED= "APPROVED"
STATE_REJECTED= "REJECTED" 

VALID_STATES={
    STATE_SUBMITTED,
    STATE_UNDER_REVIEW,
    STATE_ACTION_REQUIRED,
    STATE_VERIFIED,
    STATE_APPROVED,
    STATE_REJECTED
}

#---valid transactions matrix

VALID_TRANSACTIONS={
    STATE_SUBMITTED: [STATE_UNDER_REVIEW],
    STATE_UNDER_REVIEW: [STATE_ACTION_REQUIRED,STATE_VERIFIED, STATE_REJECTED],
    STATE_ACTION_REQUIRED: [STATE_UNDER_REVIEW,STATE_REJECTED],
    STATE_VERIFIED: [STATE_APPROVED,STATE_REJECTED],

    # Terminal state cannot do transaction anywhere

    STATE_APPROVED: [],
    STATE_REJECTED: []
}